### ISSUE TITLE
雷达图

### ISSUE THREAD

**Issue by 4cesec** [sun0225SUN/sun0225SUN#8]
你好！我想知道怎么添加这种雷达图。小白一枚，谢谢
![image](https://user-images.githubusercontent.com/80591549/193737569-2135a094-8618-4e95-964b-0e11e9150f4b.png)

**Comment by 4cesec** [comment]
我想弄一个添加到个人资料页面。代码能实现吗

**Comment by sun0225SUN** [comment]
我主页的3D贡献图右上角确实有个雷达图的组件
哈哈哈，不过我是直接用的国外大佬写好的actions实现的（复制粘贴）
    - ​uses​: ​yoshi389111/github-profile-3d-contrib@0.5.0

至于你这个需求，可以试试用echarts或者pyecharts来实现（但效果应该没那个3D图精美）或者你可以研究下那个国外大佬用的技术😂

**Comment by 4cesec** [comment]
好的呢！谢谢😘

**Comment by 4cesec** [comment]
> 我主页的3D贡献图右上角确实有个雷达图的组件 哈哈哈，不过我是直接用的国外大佬写好的actions实现的（复制粘贴） - ​uses​: ​yoshi389111/github-profile-3d-contrib@0.5.0
> 
> 至于你这个需求，可以试试用echarts或者pyecharts来实现（但效果应该没那个3D图精美）或者你可以研究下那个国外大佬用的技术😂

**Comment by 4cesec** [comment]
好的呢！谢谢😘
