### ISSUE TITLE
在Mac和Linux系统下的题图显示错误

### ISSUE THREAD

**Issue by WeebOwO** [sun0225SUN/sun0225SUN#9]
在Mac和linux系统下作者的题图会出现以下错误，即console这个单词不会显示co这两个字母，@sun0225SUN

![截图 2022-11-05 10-03-25](https://user-images.githubusercontent.com/50624245/200096379-dab1336a-8f50-41a0-a8c6-d25e3cbf1fc9.png)

**Comment by sun0225SUN** [comment]
不是系统的问题哈，就是字太多，“容器”装不下，样式设置的是居中，所以显示出现了问题。

**Comment by WeebOwO** [comment]
这个容量会随着浏览器缩放或者操作系统而变化吗，我在window上是可以正常显示的

**Comment by sun0225SUN** [comment]
这块使用的Api如下哈，具体参数和布局样式你可以参考下。
https://github.com/DenverCoder1/readme-typing-svg

**Comment by WeebOwO** [comment]
好的，那这个issue就到这里吧，我会下去研究一下这个api以及具体的问题原理。 
再次感谢您的解答。
